project 'iStrap.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DO_NOT_USE' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DO_NOT_USE

end
